export const countries = [
  { label: '🌍 Select a country', value: '', disabled: false },
  { label: '🇦🇫 Afghanistan', value: 'Afghanistan' },
  { label: '🇦🇱 Albania', value: 'Albania' },
  { label: '🇩🇿 Algeria', value: 'Algeria' },
  { label: '🇦🇩 Andorra', value: 'Andorra' },
  { label: '🇦🇴 Angola', value: 'Angola' },
  { label: '🇦🇷 Argentina', value: 'Argentina' },
  { label: '🇦🇺 Australia', value: 'Australia' },
  { label: '🇦🇹 Austria', value: 'Austria' },
  { label: '🇧🇩 Bangladesh', value: 'Bangladesh' },
  { label: '🇧🇪 Belgium', value: 'Belgium' },
  { label: '🇧🇷 Brazil', value: 'Brazil' },
  { label: '🇨🇦 Canada', value: 'Canada' },
  { label: '🇨🇳 China', value: 'China' },
  { label: '🇩🇰 Denmark', value: 'Denmark' },
  { label: '🇪🇬 Egypt', value: 'Egypt' },
  { label: '🇫🇷 France', value: 'France' },
  { label: '🇩🇪 Germany', value: 'Germany' },
  { label: '🇮🇳 India', value: 'India' },
  { label: '🇮🇩 Indonesia', value: 'Indonesia' },
  { label: '🇮🇹 Italy', value: 'Italy' },
  { label: '🇯🇵 Japan', value: 'Japan' },
  { label: '🇲🇽 Mexico', value: 'Mexico' },
  { label: '🇳🇱 Netherlands', value: 'Netherlands' },
  { label: '🇳🇿 New Zealand', value: 'New Zealand' },
  { label: '🇳🇬 Nigeria', value: 'Nigeria' },
  { label: '🇵🇰 Pakistan', value: 'Pakistan' },
  { label: '🇷🇺 Russia', value: 'Russia' },
  { label: '🇸🇦 Saudi Arabia', value: 'Saudi Arabia' },
  { label: '🇿🇦 South Africa', value: 'South Africa' },
  { label: '🇪🇸 Spain', value: 'Spain' },
  { label: '🇸🇪 Sweden', value: 'Sweden' },
  { label: '🇨🇭 Switzerland', value: 'Switzerland' },
  { label: '🇦🇪 United Arab Emirates', value: 'United Arab Emirates' },
  { label: '🇬🇧 United Kingdom', value: 'United Kingdom' },
  { label: '🇺🇸 United States', value: 'United States' },
]
export const countryPhoneCodes = [
  { label: '🌍 Select a country', value: '', disabled: false },
  { label: '🇦🇫 AF (+93)', value: '+93' },
  { label: '🇦🇱 AL (+355)', value: '+355' },
  { label: '🇩🇿 DZ (+213)', value: '+213' },
  { label: '🇦🇩 AD (+376)', value: '+376' },
  { label: '🇦🇴 AO (+244)', value: '+244' },
  { label: '🇦🇷 AR (+54)', value: '+54' },
  { label: '🇦🇺 AU (+61)', value: '+61' },
  { label: '🇦🇹 AT (+43)', value: '+43' },
  { label: '🇧🇩 BD (+880)', value: '+880' },
  { label: '🇧🇪 BE (+32)', value: '+32' },
  { label: '🇧🇷 BR (+55)', value: '+55' },
  { label: '🇨🇦 CA (+1)', value: '+1' },
  { label: '🇨🇳 CN (+86)', value: '+86' },
  { label: '🇩🇰 DK (+45)', value: '+45' },
  { label: '🇪🇬 EG (+20)', value: '+20' },
  { label: '🇫🇷 FR (+33)', value: '+33' },
  { label: '🇩🇪 DE (+49)', value: '+49' },
  { label: '🇮🇳 IN (+91)', value: '+91' },
  { label: '🇮🇩 ID (+62)', value: '+62' },
  { label: '🇮🇹 IT (+39)', value: '+39' },
  { label: '🇯🇵 JP (+81)', value: '+81' },
  { label: '🇲🇽 MX (+52)', value: '+52' },
  { label: '🇳🇱 NL (+31)', value: '+31' },
  { label: '🇳🇿 NZ (+64)', value: '+64' },
  { label: '🇳🇬 NG (+234)', value: '+234' },
  { label: '🇵🇰 PK (+92)', value: '+92' },
  { label: '🇷🇺 RU (+7)', value: '+7' },
  { label: '🇸🇦 SA (+966)', value: '+966' },
  { label: '🇿🇦 ZA (+27)', value: '+27' },
  { label: '🇪🇸 ES (+34)', value: '+34' },
  { label: '🇸🇪 SE (+46)', value: '+46' },
  { label: '🇨🇭 CH (+41)', value: '+41' },
  { label: '🇦🇪 AE (+971)', value: '+971' },
  { label: '🇬🇧 GB (+44)', value: '+44' },
  { label: '🇺🇸 US (+1)', value: '+1' },
]
